import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import assert from "node:assert/strict";
import { renderPage } from "./app/render-page.js";
import { showcaseGroups } from "./features/feature-showcase/data/showcase-groups.js";

const projectRoot = resolve(import.meta.dirname, "../../..");
const pageHtml = renderPage();

assert.match(pageHtml, /<nav class="site-nav"/);
assert.match(pageHtml, /class="brand-mark"/);
assert.match(pageHtml, /src="\/icon.svg"/);
assert.match(pageHtml, /Nexus/);
assert.match(pageHtml, /<section class="hero-section"/);
assert.match(pageHtml, /Love your TUI again/);
assert.doesNotMatch(pageHtml, /Agent-native engineering cockpit/);
assert.match(pageHtml, /<video[^>]+src="\/nexus-showcase.mp4"/);
assert.match(pageHtml, /<section class="feature-showcase"/);
assert.match(pageHtml, /data-theme-toggle/);
assert.match(pageHtml, /theme-toggle-icon\.png/);
assert.match(pageHtml, /\/scripts\/theme-toggle.js/);
assert.match(pageHtml, /data-showcase-major-link="core-plugins"/);
assert.match(pageHtml, /Core plugins/);
assert.doesNotMatch(pageHtml, /Code plugins/);
assert.match(pageHtml, /data-showcase-major-link="custom-plugins"/);
assert.match(pageHtml, /data-showcase-major-link="mini-apps"/);
assert.match(pageHtml, /data-showcase-child-link="core-plugin-savings"/);
assert.match(pageHtml, /Develop Preview Ship workflow/);
assert.match(pageHtml, /Oh My Pi LSP/);
assert.match(pageHtml, /Neo editor/);
assert.match(pageHtml, /Tetris/);
assert.doesNotMatch(pageHtml, /Git-backed knowledge capture/);
assert.match(pageHtml, /RTK includes a \/savings command/);
assert.equal(showcaseGroups.length, 3);
assert.equal(showcaseGroups.flatMap((group) => group.examples).length, 9);
assert.equal(existsSync(resolve(projectRoot, "apps/landing-page/content/features.md")), true);
assert.equal(existsSync(resolve(projectRoot, "marketing/website/features.md")), false);

const stylesheet = await readFile(resolve(projectRoot, "apps/landing-page/src/styles/features/navigation.css"), "utf8");
const tokens = await readFile(resolve(projectRoot, "apps/landing-page/src/styles/base/tokens.css"), "utf8");
const showcaseStyles = await readFile(resolve(projectRoot, "apps/landing-page/src/styles/features/showcase.css"), "utf8");
const featureNavScript = await readFile(resolve(projectRoot, "apps/landing-page/public/scripts/feature-nav.js"), "utf8");
const themeScript = await readFile(resolve(projectRoot, "apps/landing-page/public/scripts/theme-toggle.js"), "utf8");
assert.match(stylesheet, /position: sticky;/);
assert.doesNotMatch(stylesheet, /@keyframes logo-orbit-pulse/);
assert.doesNotMatch(stylesheet, /@keyframes wordmark-scan/);
assert.match(tokens, /fonts.googleapis.com/);
assert.match(tokens, /color-scheme: light/);
assert.match(tokens, /data-theme="dark"/);
assert.match(tokens, /#fafafa/);
assert.match(tokens, /--stripe-color/);
assert.match(showcaseStyles, /position: sticky;/);
assert.match(showcaseStyles, /overflow-x: auto;/);
assert.doesNotMatch(showcaseStyles, /border-radius: 64px/);
assert.match(showcaseStyles, /nth-child\(even\)/);
assert.match(showcaseStyles, /border-right: 1px solid var\(--line\)/);
assert.match(featureNavScript, /IntersectionObserver/);
assert.match(featureNavScript, /showChildLinksForGroup/);
assert.match(featureNavScript, /core-plugins/);
assert.match(themeScript, /localStorage/);
assert.match(themeScript, /data-theme-toggle-label/);
