export { checkForNexusUpdate } from "./runtime/checkForNexusUpdate";
export { compareVersions } from "./model/compareVersions";
export { createAutoUpdateModalLines } from "./ui/createAutoUpdateModalLines";
export { createUpdateInstallArgs } from "./runtime/createUpdateInstallArgs";
export { currentPackageInfo } from "./runtime/currentPackageInfo";
export { fetchLatestNpmVersion } from "./registry/fetchLatestNpmVersion";
export { installNexusUpdate } from "./runtime/installNexusUpdate";
export { isNewerVersion } from "./model/isNewerVersion";
export { generatedPackageInfo as packageInfo } from "./runtime/packageInfo.generated";
export { parseVersionParts } from "./model/parseVersionParts";
export { registerAutoUpdateExtension } from "./registerAutoUpdateExtension";
export { showAutoUpdateModal } from "./ui/showAutoUpdateModal";
