import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  clean: true,
  target: 'node26',
  exe: {
    targets: [{ platform: 'darwin', arch: 'arm64', nodeVersion: 'latest' }],
  },
  deps: {
    onlyImport: [
      '@clack/prompts',
      'console-table-printer',
      'ink',
      'ink-big-text',
      'ink-gradient',
      'react'
    ],
    alwaysBundle: [
      '@nexus/mini-apps',
      '@nexus/feature-flags',
      '@nexus/herdr',
      '@nexus/observability',
      '@nexus/pi-platform',
      '@nexus/runtime',
      '@nexus/tui-kit',
      '@extensions/ai-providers',
      '@extensions/exit-message',
      '@extensions/observations',
      '@extensions/pi-packages',
      '@extensions/runtime',
      '@extensions/startup-hero',
    ],
    onlyBundle: [
      'chalk',
      'isexe',
      'which',
      'path-key',
      'cross-spawn',
      'shebang-regex',
      'shebang-command',
      '@earendil-works/pi-coding-agent',
      'typebox',
      '@sinclair/typebox',
      '@earendil-works/pi-ai',
      'partial-json',
      '@anthropic-ai/sdk',
      'openai',
      'retry',
      'p-retry',
      'extend',
      'gaxios',
      'ms',
      'debug',
      'has-flag',
      'supports-color',
      'agent-base',
      'https-proxy-agent',
      'data-uri-to-buffer',
      'web-streams-polyfill',
      'fetch-blob',
      'formdata-polyfill',
      'node-fetch',
      'node-domexception',
      'bignumber.js',
      'json-bigint',
      'gcp-metadata',
      'google-logging-utils',
      'base64-js',
      'google-auth-library',
      'safe-buffer',
      'ecdsa-sig-formatter',
      'jws',
      'buffer-equal-constant-time',
      'jwa',
      'ws',
      'node-gyp-build',
      'bufferutil',
      'utf-8-validate',
      '@google/genai',
      '@mistralai/mistralai',
      '@opentelemetry/api',
      '@opentelemetry/semantic-conventions',
      'zod',
      'zod-to-json-schema',
      'marked',
      '@earendil-works/pi-tui',
      'get-east-asian-width',
      'highlight.js',
      'yaml',
      '@silvia-odwyer/photon-node',
      '@earendil-works/pi-telemetry',
      '@earendil-works/pi-agent-core',
      'ignore',
      'diff',
      'jiti',
      'graceful-fs',
      'signal-exit',
      'proper-lockfile',
      'balanced-match',
      'brace-expansion',
      'minimatch',
      'glob',
      'semver',
      'lru-cache',
      'hosted-git-info',
      'undici',
      'grok-mermaid',
      'cli-table3',
      'ansi-regex',
      'strip-ansi',
      'is-fullwidth-code-point',
      'emoji-regex',
      'string-width',
      '@colors/colors',
    ],
  },
})
