export type { DiffLine, ChangeStats, DiffMode, DiffViewState } from './types';
export { parseDiffLines, maxLineNumWidth } from './parsers';
export { countChanges } from './stats';
export { getDiffState, setDiffState, getDiffScrollState, resetDiffScroll } from './state';
export { padOrTruncate, rightAlign, middleTruncatePath } from './utils';
export { groupPairs, renderSplit } from './viewers/split';
export { renderUnified } from './viewers/unified';
export { renderSummary } from './viewers/summary';
export { DiffRenderer, type DiffRendererOptions } from './DiffRenderer';
export { createMutationToolDetails } from './createMutationToolDetails';
