export const CMUX_SESSION_REGISTRY_LOCK_TIMEOUT_MS = 5000;
export const CMUX_SESSION_REGISTRY_LOCK_RETRY_MS = 25;
export const CMUX_SESSION_REGISTRY_LOCK_STALE_MS = 30000;
export const CMUX_SESSION_REGISTRY_LOCK_METADATA_FILE = "owner.json";
