import type { AutomationTemplate } from "./types.js";

const groundingRules = "Use only concrete repo evidence. Cite file paths, commands, commits, PRs, jobs, and logs. Do not invent findings; label uncertainty and skip weak evidence. Prefer minimal safe changes.";

/** Bundled vendored snapshot from github.com/onurkanbakirci/awesome-codex-automations. */
export const automationTemplates: AutomationTemplate[] = [
	["daily-bug-scan", "Daily Bug Scan", "Scan recent commits for likely bugs and propose minimal fixes.", "daily"],
	["test-gap-detection", "Test Gap Detection", "Identify untested paths from recent changes and add focused tests.", "daily"],
	["nightly-ci-report", "Nightly CI Report", "Summarize CI failures and flaky tests; suggest top fixes.", "daily at 8am"],
	["ci-monitor", "CI Monitor", "Check CI failures; group by likely root cause and suggest minimal fixes.", "every 4h"],
	["pre-release-check", "Pre-release Check", "Before tagging, verify changelog, migrations, feature flags, and tests.", "daily"],
	["standup-summary", "Standup Summary", "Summarize yesterday's git activity for standup.", "weekdays at 9am"],
	["weekly-pr-summary", "Weekly PR Summary", "Summarize last week's PRs by teammate and theme; highlight risks.", "0 9 * * 1"],
	["weekly-engineering-summary", "Weekly Engineering Summary", "Synthesize this week's PRs, rollouts, incidents, and reviews.", "0 10 * * 5"],
	["weekly-release-notes", "Weekly Release Notes", "Draft weekly release notes from merged PRs.", "0 11 * * 5"],
	["update-changelog", "Update Changelog", "Update the changelog with this week's highlights and key PR links.", "0 12 * * 5"],
	["dependency-and-sdk-drift", "Dependency and SDK Drift", "Detect dependency and SDK drift and propose a minimal alignment plan.", "0 9 * * 1"],
	["dependency-sweep", "Dependency Sweep", "Scan outdated dependencies; propose safe upgrades with minimal changes.", "0 10 * * 1"],
	["performance-regression-watch", "Performance Regression Watch", "Compare recent changes to benchmarks or traces and flag regressions early.", "daily"],
	["performance-audit", "Performance Audit", "Audit performance regressions and propose highest-leverage fixes.", "0 9 * * 2"],
	["issue-triage", "Issue Triage", "Triage new issues; suggest owner, priority, and labels.", "every 4h"],
	["update-agents-md", "Update AGENTS.md", "Update AGENTS.md with newly discovered workflows and commands.", "0 16 * * 5"],
	["skill-progression-map", "Skill Progression Map", "From recent PRs and reviews, suggest next skills to deepen.", "0 15 * * 5"],
	["daily-classic-game", "Daily Classic Game", "Create a small classic game with minimal scope.", "daily"],
	["code-smell-detector", "Code Smell Detector", "Analyze recent changes for code smells and anti-patterns.", "daily"],
	["dead-code-hunter", "Dead Code Hunter", "Identify potentially unused code in recently modified files.", "0 13 * * 3"],
	["weekly-changelog-generator", "Weekly Changelog Generator", "Generate a human-readable changelog from merged PRs.", "0 9 * * 5"],
	["pr-review-reminder", "PR Review Reminder", "Identify PRs awaiting review for more than 48 hours.", "0 10 * * 1-5"],
	["readme-freshness-check", "README Freshness Check", "Verify that README and core docs are still accurate.", "0 11 * * 3"],
	["api-documentation-drift", "API Documentation Drift", "Detect mismatches between API docs and implementations.", "0 12 * * 3"],
	["new-contributor-guide-validator", "New Contributor Guide Validator", "Ensure onboarding docs work with current repo state.", "0 10 * * 2"],
	["dependency-update-digest", "Dependency Update Digest", "Summarize available dependency updates and changelogs.", "0 9 * * 1"],
	["license-compliance-check", "License Compliance Check", "Scan dependencies for license compatibility issues.", "0 14 * * 4"],
	["unused-dependency-finder", "Unused Dependency Finder", "Identify declared but unused dependencies.", "0 15 * * 3"],
	["secret-scanner", "Secret Scanner", "Scan recent commits for accidentally committed secrets.", "daily"],
	["security-advisory-monitor", "Security Advisory Monitor", "Check dependencies for new CVEs or security advisories.", "every 4h"],
	["permission-audit", "Permission Audit", "Review repository access permissions and flag anomalies.", "0 9 * * 1"],
	["test-coverage-trend", "Test Coverage Trend", "Track test coverage changes and flag declining areas.", "0 10 * * 5"],
	["flaky-test-detector", "Flaky Test Detector", "Identify tests with inconsistent pass/fail results.", "daily"],
	["test-gap-analyzer", "Test Gap Analyzer", "Find recently modified code paths lacking test coverage.", "daily"],
	["release-notes-drafter", "Release Notes Drafter", "Draft release notes from commits since the last tag.", "0 12 * * 5"],
	["version-bump-advisor", "Version Bump Advisor", "Recommend semantic version bump based on changes.", "0 13 * * 5"],
	["migration-script-validator", "Migration Script Validator", "Verify migration scripts are reversible and consistent.", "0 14 * * 2"],
].map(([id, name, description, defaultSchedule]) => ({ id, name, description, defaultSchedule, prompt: `${description}\n\n${groundingRules}` }));
