import type { AiProviderDefinition } from "./AiProviderDefinition.js";

/**
 * OAuth/login providers listed by oh-my-pi's provider registry.
 */
export const ohMyPiProviderDefinitions: AiProviderDefinition[] = [
  { id: "anthropic", name: "Anthropic (Claude Pro/Max)", credentialLabel: "OAuth access token" },
  { id: "alibaba-coding-plan", name: "Alibaba Coding Plan", credentialLabel: "API key or access token" },
  { id: "openai-codex", name: "ChatGPT Plus/Pro (Codex Subscription)", credentialLabel: "OAuth access token" },
  { id: "gitlab-duo", name: "GitLab Duo", credentialLabel: "OAuth access token" },
  { id: "kimi-code", name: "Kimi Code", credentialLabel: "OAuth access token" },
  { id: "kilo", name: "Kilo Gateway", credentialLabel: "API key" },
  { id: "kagi", name: "Kagi", credentialLabel: "API key" },
  { id: "cerebras", name: "Cerebras", credentialLabel: "API key" },
  { id: "fireworks", name: "Fireworks", credentialLabel: "API key" },
  { id: "github-copilot", name: "GitHub Copilot", credentialLabel: "OAuth access token" },
  { id: "google-gemini-cli", name: "Google Cloud Code Assist (Gemini CLI)", credentialLabel: "OAuth access token" },
  { id: "google-antigravity", name: "Antigravity (Gemini 3, Claude, GPT-OSS)", credentialLabel: "OAuth access token" },
  { id: "cursor", name: "Cursor (Claude, GPT, etc.)", credentialLabel: "Cursor access token" },
  { id: "litellm", name: "LiteLLM", credentialLabel: "API key" },
  { id: "lm-studio", name: "LM Studio (Local OpenAI-compatible)", credentialLabel: "API key or local token" },
  { id: "ollama", name: "Ollama (Local OpenAI-compatible)", credentialLabel: "API key or local token" },
  { id: "ollama-cloud", name: "Ollama Cloud", credentialLabel: "API key" },
  { id: "huggingface", name: "Hugging Face Inference", credentialLabel: "API key" },
  { id: "synthetic", name: "Synthetic", credentialLabel: "API key" },
  { id: "tavily", name: "Tavily", credentialLabel: "API key" },
  { id: "together", name: "Together", credentialLabel: "API key" },
  { id: "xiaomi", name: "Xiaomi MiMo", credentialLabel: "API key" },
  { id: "opencode-zen", name: "OpenCode Zen", credentialLabel: "API key" },
  { id: "opencode-go", name: "OpenCode Go", credentialLabel: "API key" },
  { id: "zai", name: "Z.AI (GLM Coding Plan)", credentialLabel: "API key" },
  { id: "minimax-code", name: "MiniMax Coding Plan (International)", credentialLabel: "API key" },
  { id: "minimax-code-cn", name: "MiniMax Coding Plan (China)", credentialLabel: "API key" },
  { id: "moonshot", name: "Moonshot (Kimi API)", credentialLabel: "API key" },
  { id: "nanogpt", name: "NanoGPT", credentialLabel: "API key" },
  { id: "parallel", name: "Parallel", credentialLabel: "API key" },
  { id: "perplexity", name: "Perplexity (Pro/Max)", credentialLabel: "API key or cookie" },
  { id: "nvidia", name: "NVIDIA", credentialLabel: "API key" },
  { id: "qwen-portal", name: "Qwen Portal", credentialLabel: "OAuth token or API key" },
  { id: "qianfan", name: "Qianfan", credentialLabel: "API key" },
  { id: "venice", name: "Venice", credentialLabel: "API key" },
  { id: "zenmux", name: "ZenMux", credentialLabel: "API key" },
  { id: "vllm", name: "vLLM (Local OpenAI-compatible)", credentialLabel: "API key or local token" },
  { id: "cloudflare-ai-gateway", name: "Cloudflare AI Gateway", credentialLabel: "API key" },
  { id: "vercel-ai-gateway", name: "Vercel AI Gateway", credentialLabel: "API key" },
];
